### PR TITLE
Merge feature/CLIGameEngine

### LINKED ISSUE #52: GameEngine: create and test
Create a new class (provisional name "GameEngine") which is in charge of starting a new game, interact with the user via the command line and call the proper methods of the Game class (check win, change round, actions).

It is necessary that the system asks users to provide an input until a valid command in provided, catching exceptions thrown by invalid inputs or actions (and printing a proper message).

This class should also inform the user about the syntax to use to insert commands.

Create related tests, if necessary using a Test Double.

### PR DESCRIPTION
**Pull request by matfumis**
Added the command line game engine implementation, which allows to crate and play a Quoridor match from the command line. Resolves #52

### CODE REVIEW

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package it.units.sdm.quoridor.cli.engine;
+
+import it.units.sdm.quoridor.model.AbstractGame;
+
+public interface QuoridorGameEngine {
+
+  AbstractGame createGame();
+
+  void startGame(AbstractGame game);
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java]:
```suggestion
  void startGame();
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/InputProvider.java
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/InputProvider.java:1]: There is no need to create this interface. You could use `Reader` interface instead.

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIInputProvider.java
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIInputProvider.java:1]: There is no need to create this class: the wanted `Reader` can be passed as an argument in the constructor of the GameEngine class.

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+import java.util.Objects;
+import java.util.Optional;
+
+
+public class CLIGameEngine implements QuoridorGameEngine {
+
+  private final InputProvider inputProvider;
+  private final QuoridorParser parser;
+
+  private boolean testingMode = false;
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]: It doesn't seem good... It is not a good idea to include code for testing the class into the production code.
Create and use a **Test Double** instead.

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java [hunk 3]
```diff
@@ -0,0 +1,12 @@
+package it.units.sdm.quoridor.cli.engine;
+
+import it.units.sdm.quoridor.model.AbstractGame;
+
+public interface QuoridorGameEngine {
+
+  AbstractGame createGame();
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java]:
```suggestion

```

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java [hunk 4]
```diff
@@ -0,0 +1,12 @@
...
+
+  void startGame(AbstractGame game);
+
+  void endGame();
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java]:
```suggestion

```

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java [hunk 5]
```diff
@@ -0,0 +1,12 @@
+package it.units.sdm.quoridor.cli.engine;
+
+import it.units.sdm.quoridor.model.AbstractGame;
+
+public interface QuoridorGameEngine {
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java]:
```suggestion
public abstract class QuoridorGameEngine {
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java:7]:
```suggestion
  private final Reader reader;
  private final AbstractQuoridorBuilder builder;
  private final QuoridorParser parser;
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+
+  public CLIGameEngine(InputProvider inputProvider, QuoridorParser parser) {
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
  public CLIGameEngine(Reader reader, QuoridorParser parser, AbstractQuoridorBuilder builder) {
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+    this.inputProvider = inputProvider;
+    this.parser = parser;
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
    this.reader= reader;
    this.parser = parser;
    this.builder = builder;
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 9]
```diff
@@ -0,0 +1,115 @@
...
+import it.units.sdm.quoridor.utils.Position;
+
+import java.util.Objects;
+import java.util.Optional;
+
+
+public class CLIGameEngine implements QuoridorGameEngine {
+
+  private final InputProvider inputProvider;
+  private final QuoridorParser parser;
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
  private final Reader reader;
  private final QuoridorParser parser;
  private final AbstractQuoridorBuilder builder;
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 10]
```diff
@@ -0,0 +1,115 @@
...
+      try {
+        int numPlayers = Integer.parseInt(inputProvider.nextLine());
+        BuilderDirector builderDirector = new BuilderDirector(new StdQuoridorBuilder(numPlayers));
+        game = builderDirector.makeGame();
+      } catch (InvalidParameterException | BuilderException | NumberFormatException e) {
+        System.out.println("Enter a valid number:");
+      }
+    }
+    return game;
+  }
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
```

Anyway, keep this code available for future improvements.

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 11]
```diff
@@ -0,0 +1,115 @@
...
+
+  @Override
+  public void startGame(AbstractGame game) {
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]: Before, create a new game using the provider builder via a private method.
You can instantiate a BuilderDirector directly here.

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 12]
```diff
@@ -0,0 +1,115 @@
...
+    }
+    game.changeRound();
+  }
+
+  private void performCommand(String command, AbstractGame game) {
+    boolean commandExecuted = false;
+    while (!commandExecuted) {
+      try {
+        parser.acceptAndParse(command);
+        Optional<Position> targetPosition = parser.getActionPosition();
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]: Use ```.orElseThrow()``` and avoid the ```null``` case.

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 13]
```diff
@@ -0,0 +1,115 @@
...
+
+  @Override
+  public void endGame() {
+    System.out.println("Game over!");
+  }
+
+  private void executeRound(AbstractGame game) {
+    printWallsConvention();
+
+    String command = inputProvider.nextLine();
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
    String command = reader.nextLine();
```

File: src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java [hunk 14]
```diff
@@ -0,0 +1,115 @@
...
+      executeRound(game);
+
+      if (testingMode) {
+        break;
+      }
+    }
+  }
+
+  @Override
+  public void endGame() {
```
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/CLIGameEngine.java]:
```suggestion
  private void endGame() {
```

**Review by AM311 — CHANGES_REQUESTED** [review]
@matfumis Try to improve the code applying the suggested changes.
A new revision will be made after this.

File: src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java
Comment (AM311) [inline src/main/java/it/units/sdm/quoridor/cli/engine/QuoridorGameEngine.java:1]: Please, make the following changes (updates some of the inline comments):
- Move the `QuoridorGameEngine` **abstract class** in the (new) `quoridor.engine` package;
  - This abstract class should have only the `AbstractQuoridorBuilder` field (and, of course, the `startGame()` method);
- **Extend** this class, creating the `CLIQuoridorGameEngine` **abstract class**, which has also two fields of type `Reader` and `Writer`
- In the package `quoridor.cli`, move the class `CLIGameEngine` and rename it `StandardCLIQuoridorGameEngine`. Make sure that this class extends `CLIQuoridorGameEngine`

**Review by AM311 — CHANGES_REQUESTED** [review]
@matfumis small update of the needed reviews.

**Review by AM311 — APPROVED** [review]
OK, some minor changes will be performed after the CLI branch is merged, too.
